version: "3"
services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./statamic:/var/www/statamic-site/
  fpm:
    build:
      context: ./
      dockerfile: fpm.Dockerfile
    volumes:
      - ./statamic:/var/www/statamic-site/
